apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: {{VERSION}}
controlPlaneEndpoint: "{{MASTER_VIP}}:6443"
networking:
    # This CIDR is a Calico default. Substitute or remove for your CNI provider.
    podSubnet: "{{POD_CIDR}}"
imageRepository: registry.cn-hangzhou.aliyuncs.com/imooc
